In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('../Data/Raw_Data/airbnb_dataset.csv')

In [4]:
df.shape

(20120, 27)

In [5]:
df.columns

Index(['listing_id', 'host_id', 'host_name', 'neighbourhood', 'city',
       'room_type', 'property_type', 'price', 'minimum_nights',
       'number_of_reviews', 'reviews_per_month', 'availability_365',
       'latitude', 'longitude', 'host_since', 'last_review', 'rating', 'beds',
       'bedrooms', 'bathrooms', 'guests', 'instant_bookable',
       'cancellation_policy', 'host_response_rate', 'listing_status', 'device',
       'payment_method'],
      dtype='str')

In [6]:
df.head()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,...,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
0,107345,10276,NaN,Bronx,New York City,Hotel room,apartment,213.62,27,51,...,NaN,-1.0,1 bath,8.0,T,strict_14_with_grace_period,NaN,NaN,NaN,PayPal
1,109454,5049,Emma,Manhattan,NYC,Private Room,Guest suite,289,15,38,...,-1.0,6.0,1.5,10.0,False,MODERATE,80,NaN,tablet,Card
2,119857,11567,Sophia,Manhattan,NYC,Private room,NaN,130.82,24,39,...,NaN,4.0,1 bath,NaN,t,strict,NaN,active,Mobile,Card
3,108591,5546,NaN,Queens,NYC,Entire home/apt,Apartment,36.43,13,49,...,3.0,4.0,2.5 baths,12.0,True,moderate,100%,Active,Mobile,NaN
4,117164,8693,Michael,Staten Island,New York,entire home/apt,Loft,271.74,21,41,...,10.0,3.0,1.5 bath,4.0,T,MODERATE,85 %,AVAILABLE,mobile,cash

In [7]:
df.tail()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,...,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
20115,111285,11257,Sophia,Brooklyn,New York,Shared room,Townhouse,68.76,365,44,...,1.0,1.0,3 baths,1.0,NaN,strict_14_with_grace_period,NaN,available,desktop,cash
20116,111965,8929,David,Bronx,New York,Private Room,Guest suite,69.01,19,30,...,NaN,5.0,1 bath,6.0,F,strict_14_with_grace_period,90%,Active,Desktop,Card
20117,105391,10739,Michael,Staten Island,New York,entire home/apt,apartment,280.07,12,42,...,10.0,-1.0,2,2.0,F,strict_14_with_grace_period,80,Active,desktop,cash
20118,100861,8325,John Smith,Brooklyn,NYC,Shared room,NaN,476.49,365,44,...,8.0,NaN,NaN,1.0,NaN,MODERATE,100%,available,Mobile,PayPal
20119,115796,5659,NaN,Queens,NYC,Private Room,Townhouse,84.16,3650,61,...,4.0,2.0,1 bath,3.0,f,strict,100%,available,Desktop,card

In [8]:
df.dtypes

listing_id               int64
host_id                  int64
host_name                  str
neighbourhood              str
city                       str
room_type                  str
property_type              str
price                      str
minimum_nights           int64
number_of_reviews        int64
reviews_per_month      float64
availability_365         int64
latitude               float64
longitude              float64
host_since                 str
last_review                str
rating                 float64
beds                   float64
bedrooms               float64
bathrooms                  str
guests                 float64
instant_bookable           str
cancellation_policy        str
host_response_rate         str
listing_status             str
device                     str
payment_method             str
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20120 entries, 0 to 20119
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           20120 non-null  int64
 1   host_id              20120 non-null  int64
 2   host_name            16495 non-null  str
 3   neighbourhood        20120 non-null  str
 4   city                 20120 non-null  str
 5   room_type            20120 non-null  str
 6   property_type        17838 non-null  str
 7   price                19637 non-null  str
 8   minimum_nights       20120 non-null  int64
 9   number_of_reviews    20120 non-null  int64
 10  reviews_per_month    18509 non-null  float64
 11  availability_365     20120 non-null  int64
 12  latitude             20120 non-null  float64
 13  longitude            20120 non-null  float64
 14  host_since           20120 non-null  str
 15  last_review          18105 non-null  str
 16  rating               19113 non-null  float64
 17  beds                 18472 non-null  float64
 18  bedrooms             16701 non-null  float64
 19  bathrooms            17817 non-null  str
 20  guests               17373 non-null  float64
 21  instant_bookable     17205 non-null  str
 22  cancellation_policy  20120 non-null  str
 23  host_response_rate   16789 non-null  str
 24  listing_status       16836 non-null  str
 25  device               16776 non-null  str
 26  payment_method       16737 non-null  str
dtypes: float64(7), int64(5), str(15)
memory usage: 4.1 MB

In [10]:
df.isnull().sum()

listing_id                0
host_id                   0
host_name              3625
neighbourhood             0
city                      0
room_type                 0
property_type          2282
price                   483
minimum_nights            0
number_of_reviews         0
reviews_per_month      1611
availability_365          0
latitude                  0
longitude                 0
host_since                0
last_review            2015
rating                 1007
beds                   1648
bedrooms               3419
bathrooms              2303
guests                 2747
instant_bookable       2915
cancellation_policy       0
host_response_rate     3331
listing_status         3284
device                 3344
payment_method         3383
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(120)

In [12]:
df.nunique()

listing_id             20000
host_id                 6590
host_name                  6
neighbourhood              9
city                       4
room_type                  7
property_type              8
price                  14115
minimum_nights            36
number_of_reviews         52
reviews_per_month        837
availability_365         366
latitude               18982
longitude              19125
host_since              3868
last_review             3859
rating                   217
beds                      11
bedrooms                   8
bathrooms                  8
guests                     9
instant_bookable           6
cancellation_policy        6
host_response_rate         5
listing_status             5
device                     5
payment_method             5
dtype: int64

In [13]:
df.describe()

,listing_id,host_id,minimum_nights,number_of_reviews,reviews_per_month,availability_365,latitude,longitude,rating,beds,bedrooms,guests
count,20120.000000,20120.000000,20120.000000,20120.000000,18509.000000,20120.00000,20120.000000,20120.000000,19113.000000,18472.000000,16701.000000,17373.000000
mean,110000.369930,8487.921968,154.248260,45.038867,2.042103,183.01829,40.612102,-73.910002,4.328414,4.098744,2.498773,5.658551
std,5773.090391,2007.642717,595.946473,6.664779,1.559679,105.52314,3.792597,5.926442,0.424861,3.317367,2.284591,3.498071
min,100001.000000,5002.000000,1.000000,17.000000,0.010000,0.00000,-95.000000,-200.000000,2.370000,-1.000000,-1.000000,1.000000
25%,104993.750000,6753.750000,10.000000,40.000000,0.900000,91.00000,40.683333,-74.005127,4.040000,1.000000,1.000000,3.000000
50%,110000.500000,8485.000000,18.000000,45.000000,1.670000,185.00000,40.720455,-73.960304,4.340000,4.000000,3.000000,5.000000
75%,115001.250000,10227.250000,27.000000,49.000000,2.760000,274.00000,40.756607,-73.916278,4.650000,7.000000,4.000000,8.000000
max,120000.000000,11999.000000,3650.000000,71.000000,13.680000,365.00000,95.000000,200.000000,5.000000,10.000000,6.000000,12.000000

In [14]:
df.select_dtypes(include="number").columns

Index(['listing_id', 'host_id', 'minimum_nights', 'number_of_reviews',
       'reviews_per_month', 'availability_365', 'latitude', 'longitude',
       'rating', 'beds', 'bedrooms', 'guests'],
      dtype='str')

In [15]:
print(df['host_since'].head())

0    2022-06-09
1    2017-07-20
2    2018-06-10
3    2020-02-23
4    2024-07-11
Name: host_since, dtype: str

In [16]:
print(df['last_review'].head())

0    2015-07-05
1           NaN
2    2023-06-02
3    2020-11-17
4    2023-12-02
Name: last_review, dtype: str