In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
data=np.array(['g','f','e','f','k','l','k'])
print(data)
print(type(data))

['g' 'f' 'e' 'f' 'k' 'l' 'k']
<class 'numpy.ndarray'>

In [6]:
s=pd.Series(data)
print("pandas Series",s)
print(type(s))

pandas Series 0    g
1    f
2    e
3    f
4    k
5    l
6    k
dtype: object
<class 'pandas.core.series.Series'>

In [9]:
a=[2,3,43,4,54,8]
print(a)

[2, 3, 43, 4, 54, 8]

In [11]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [12]:
df=pd.DataFrame(a)
print(df)

    0
0   2
1   3
2  43
3   4
4  54
5   8

In [14]:
d={
    "name":["abhishek","riya"],
    "age":[21,23],
    "city":["jaipur","delhi"]
}
df = pd.DataFrame(d)
df

       name  age    city
0  abhishek   21  jaipur
1      riya   23   delhi

In [16]:
d={
    "name":["abhishek","riya"],
    "age":[21,23],
    "city":["jaipur","delhi"]
}
df = pd.DataFrame(d)
df
# df.to_csv("bans.csv")
df
df.to_csv("bans.csv",index=False)
df

       name  age    city
0  abhishek   21  jaipur
1      riya   23   delhi